version: '3.8'
services:

  postgres:
    container_name: 'be-prisma-postgres'
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - be-prisma-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    container_name: 'be-prisma-adminer'
    image: adminer
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes:
  be-prisma-postgres: